version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: resource-backend

    restart: always

    ports:
      - "5000:3000"

    env_file:
      - ./backend/.env

  frontend:

    build:
      context: ./client

    container_name: resource-frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend